# =============================================================================
# RNA Motif Discovery Explorer
# Script: report_generation.R
# Purpose: CSV exports, PDF reports, downloadable plot files
# =============================================================================

library(dplyr)
library(ggplot2)
library(knitr)
library(rmarkdown)
library(writexl)

# -----------------------------------------------------------------------------
# export_motif_table_csv
# Exports the full motif ranking table to CSV.
# -----------------------------------------------------------------------------
export_motif_table_csv <- function(motif_table, out_path) {
  df_clean <- motif_table %>%
    select(
      kmer, total_count, seq_count, seq_frequency,
      observed_freq, expected_freq, enrichment_score,
      p_value, p_adjusted, significant,
      rank_freq, rank_enrichment, rank_significance, combined_rank
    ) %>%
    mutate(across(where(is.numeric), ~round(.x, 6)))

  write.csv(df_clean, file = out_path, row.names = FALSE)
  invisible(out_path)
}

# -----------------------------------------------------------------------------
# export_stats_csv
# Exports per-sequence statistics to CSV.
# -----------------------------------------------------------------------------
export_stats_csv <- function(per_seq_stats, out_path) {
  df_clean <- per_seq_stats %>%
    mutate(across(where(is.numeric), ~round(.x, 4)))

  write.csv(df_clean, file = out_path, row.names = FALSE)
  invisible(out_path)
}

# -----------------------------------------------------------------------------
# export_positional_csv
# Exports positional distribution data to CSV.
# -----------------------------------------------------------------------------
export_positional_csv <- function(pos_dist, out_path) {
  if (is.null(pos_dist) || nrow(pos_dist) == 0) {
    write.csv(data.frame(message = "No positional data available"),
              file = out_path, row.names = FALSE)
    return(invisible(out_path))
  }

  df_clean <- pos_dist %>%
    mutate(across(where(is.numeric), ~round(.x, 4)))

  write.csv(df_clean, file = out_path, row.names = FALSE)
  invisible(out_path)
}

# -----------------------------------------------------------------------------
# save_plot_png
# Saves a ggplot to PNG with consistent dimensions.
# -----------------------------------------------------------------------------
save_plot_png <- function(plot_obj, out_path,
                            width = 10, height = 6, dpi = 150) {
  if (is.null(plot_obj)) {
    warning("Cannot save NULL plot.")
    return(invisible(NULL))
  }
  ggsave(out_path, plot = plot_obj, width = width, height = height,
         dpi = dpi, bg = "#0D1117")
  invisible(out_path)
}

# -----------------------------------------------------------------------------
# generate_rmd_report
# Creates an R Markdown report and renders it to PDF.
# All data is passed as parameters to avoid global state dependencies.
# -----------------------------------------------------------------------------
generate_rmd_report <- function(summary_stats, motif_table, top_motifs,
                                 per_seq_stats, params_list,
                                 out_dir = "outputs/reports") {
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  rmd_path  <- file.path(out_dir, "rna_motif_report.Rmd")
  pdf_path  <- file.path(out_dir, "rna_motif_report.pdf")

  # Write the Rmd template
  rmd_content <- sprintf('
---
title: "RNA Motif Discovery Report"
subtitle: "Generated by RNA Motif Discovery Explorer"
date: "`r format(Sys.time(), \'%%Y-%%m-%%d %%H:%%M\')`"
output:
  pdf_document:
    toc: true
    number_sections: true
    highlight: tango
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(knitr)
library(ggplot2)
```

# Dataset Summary

```{r summary}
stats_df <- data.frame(
  Metric = c("Total Sequences", "Mean Length (nt)", "Median Length (nt)",
             "Min Length (nt)", "Max Length (nt)", "Mean GC Content",
             "Total Nucleotides", "Motif Length Analysed",
             "Unique k-mers Found", "k-mers After Filter"),
  Value = c(
    %d, %.1f, %.1f, %d, %d,
    sprintf("%%.1f%%%%", %.3f * 100),
    format(%d, big.mark = ","),
    %d, %d, %d
  )
)
kable(stats_df, caption = "Dataset Overview", booktabs = TRUE)
```

# Top Motifs

```{r motifs}
top_df <- head(motif_table, 20)[, c("kmer","total_count","seq_frequency",
                                     "enrichment_score","p_adjusted","significant")]
top_df$seq_frequency <- round(top_df$seq_frequency, 3)
top_df$enrichment_score <- round(top_df$enrichment_score, 3)
top_df$p_adjusted <- formatC(top_df$p_adjusted, format = "e", digits = 2)
colnames(top_df) <- c("k-mer","Total Count","Seq Freq","Enrichment","Adj p","Sig")
kable(top_df, caption = "Top 20 Motifs by Rank", booktabs = TRUE)
```

# Analysis Parameters

```{r params}
params_df <- data.frame(
  Parameter = c("Input File", "k-mer Length", "Min Sequence Frequency",
                "Min Occurrence Count"),
  Value = c("%s", %d, %.2f, %d)
)
kable(params_df, caption = "Analysis Parameters", booktabs = TRUE)
```

# Notes

- Enrichment scores are log2 ratios vs. uniform background model (p=0.25 per base).
- P-values computed via one-sided binomial test; Bonferroni corrected.
- Combined rank aggregates frequency, enrichment, and significance ranks.
',
    summary_stats$total_sequences,
    summary_stats$mean_length,
    summary_stats$median_length,
    summary_stats$min_length,
    summary_stats$max_length,
    summary_stats$mean_gc,
    summary_stats$total_nucleotides,
    params_list$k,
    params_list$total_kmers_found,
    params_list$kmers_after_filter,
    params_list$filepath,
    params_list$k,
    params_list$min_freq,
    params_list$min_count
  )

  writeLines(rmd_content, rmd_path)

  tryCatch({
    rmarkdown::render(rmd_path,
                       output_file = pdf_path,
                       envir       = list(motif_table = motif_table),
                       quiet       = TRUE)
    pdf_path
  }, error = function(e) {
    warning(sprintf("PDF rendering failed: %s", conditionMessage(e)))
    NULL
  })
}

# -----------------------------------------------------------------------------
# prepare_all_downloads
# Bundles all export files, returns named list of file paths.
# -----------------------------------------------------------------------------
prepare_all_downloads <- function(motif_result, preproc_result,
                                   out_dir = "outputs") {
  dir.create(file.path(out_dir, "reports"), showWarnings = FALSE,
             recursive = TRUE)

  paths <- list()

  # Motif table CSV
  paths$motif_csv <- file.path(out_dir, "reports", "motif_table.csv")
  export_motif_table_csv(motif_result$motif_table, paths$motif_csv)

  # Sequence stats CSV
  paths$stats_csv <- file.path(out_dir, "reports", "sequence_stats.csv")
  export_stats_csv(preproc_result$stats$per_sequence, paths$stats_csv)

  # Positional distribution CSV
  paths$pos_csv <- file.path(out_dir, "reports", "positional_distribution.csv")
  export_positional_csv(motif_result$positional_dist, paths$pos_csv)

  paths
}
